// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  // TODO (codelab user): Replace with your Firebase credentials

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm5tQ8xCJ5izDraVpmDhgPwNABCzi3uMA',
    appId: '1:578987021233:web:254d1484a2d02accde2390',
    messagingSenderId: '578987021233',
    projectId: 'flutterfire-ui-codelab-7c692',
    authDomain: 'flutterfire-ui-codelab-7c692.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-7c692.firebasestorage.app',
  );

  // Generate this file with credentials with the FlutterFire CLI

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHKWY9f7nSWZEBgvrgek8v_20Fu84QTtU',
    appId: '1:578987021233:android:62c03e43fb47736dde2390',
    messagingSenderId: '578987021233',
    projectId: 'flutterfire-ui-codelab-7c692',
    storageBucket: 'flutterfire-ui-codelab-7c692.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm6uRo7xK_wWleXoIlBHZLdfo9CtmSpYk',
    appId: '1:578987021233:ios:83003bc7b1b0203fde2390',
    messagingSenderId: '578987021233',
    projectId: 'flutterfire-ui-codelab-7c692',
    storageBucket: 'flutterfire-ui-codelab-7c692.firebasestorage.app',
    iosBundleId: 'com.example.start',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm6uRo7xK_wWleXoIlBHZLdfo9CtmSpYk',
    appId: '1:578987021233:ios:83003bc7b1b0203fde2390',
    messagingSenderId: '578987021233',
    projectId: 'flutterfire-ui-codelab-7c692',
    storageBucket: 'flutterfire-ui-codelab-7c692.firebasestorage.app',
    iosBundleId: 'com.example.start',
  );

}